### ISSUE TITLE
Root manifest not found

### ISSUE THREAD

**Issue by SplittyDev** [fwal/setup-swift#133]
**Describe the bug**
After setting up the workflow, it fails with the following message:
```console
> Run swift build -v
/usr/bin/xcrun --sdk macosx --show-sdk-path
/usr/bin/xcrun --sdk macosx --show-sdk-platform-path
/usr/bin/xcrun --sdk macosx --find xctest
/Users/runner/hostedtoolcache/swift-macOS/5.3/x64/usr/bin/swiftc -print-target-info
error: root manifest not found
Error: Process completed with exit code 1.
```

To be honest I'm not completely sure that this is a bug in the workflow.
Is running the workflow like this supported for Swift Packages?

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): macos-latest
 - Swift version (`swift-version`): 5.3

My workflow file:
```yml
name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3"
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
```

The PR adding the workflow:
https://github.com/Quintschaf/SchafKit/pull/3

**Comment by fwal** [comment]
Hi @SplittyDev! Thanks for your report!
It looks like its due to that you source code isn't available for swift to build. By default, the source in your repo isn't available in the workflow.
Try adding `- uses: actions/checkout@v2` to checkout your source in your workflow before the build step.

**Comment by SplittyDev** [comment]
Hi @fwal, thanks for the quick reply!
The repo is getting checked out now, I'm getting another error though:

```
Target: x86_64-apple-darwin19.6.0
connect EHOSTUNREACH 169.47.73.10:443
Waiting 17 seconds before trying again
connect EHOSTUNREACH 169.47.73.10:443
Waiting 10 seconds before trying again
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
```

No idea what causes this..

**Comment by fwal** [comment]
Haven't seen that one before. Does it display a stacktrace? Have you tried running the workflow again?

**Comment by SplittyDev** [comment]
> Haven't seen that one before. Does it display a stacktrace? Have you tried running the workflow again?

I tried running it again multiple times, just to be sure that it's not a temporary error.
Just ran it again, this is the output:

```
> Run fwal/setup-swift@v1
/usr/bin/xcrun --toolchain swift 5.3 --run swift --version
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.6.0
connect EHOSTUNREACH 169.47.73.10:443
Waiting 20 seconds before trying again
connect EHOSTUNREACH 169.47.73.10:443
Waiting 18 seconds before trying again
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
connect EHOSTUNREACH 169.47.73.10:443
Stacktrace:
Error: connect EHOSTUNREACH 169.47.73.10:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
```

I tried finding out which host it's trying to connect to. Couldn't find the IP in the repo at all.

<img width="788" alt="Screen Shot 2020-10-06 at 16 26 31" src="https://user-images.githubusercontent.com/4216049/95214942-b3802f80-07f0-11eb-8377-afc9c53b714e.png">

**Comment by fwal** [comment]
Oh... Well then that settles that 😅

**Comment by SplittyDev** [comment]
I'll keep the issue open till swift.org is back up if that's alright with you

**Comment by fwal** [comment]
@SplittyDev swift.org seems to be back online 👍🏻

**Comment by fwal** [comment]
Created #135 for that specific case.
