### ISSUE TITLE
"Unexpected error, unable to continue.  Please report at…". 404  

### ISSUE THREAD

**Issue by haikusw** [fwal/setup-swift#202]
**Describe the bug**

Reporting as directed:

**_Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues_**

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): ubuntu 20.04.2 (error), macOS 11.3, 11.4, & 12 (succeeds)
 - Swift version (`swift-version`): 5.1, 5.2, 5.3.

https://github.com/mxcl/swift-sh/runs/2274556387?check_suite_focus=true

console:

> 3s
1
Run fwal/setup-swift@v1
2
  with:
3
    swift-version: 5.1
4
/usr/bin/gpg --import /home/runner/work/_temp/79daf884-b394-4344-b457-8c15c78e2d21
5
gpg: directory '/home/runner/.gnupg' created
6
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
7
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
8
gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
9
gpg: key 9F597F4D21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
10
gpg: key 63BC1CFE91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
11
gpg: key EF5430F071E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
12
gpg: key 7638F1FB2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
13
gpg: key 925CC1CCED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
14
gpg: key FAF6989E1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
15
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" 1 new signature
16
gpg: Total number processed: 8
17
gpg:               imported: 7
18
gpg:         new signatures: 1
19
/usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
20
gpg: refreshing 7 keys from hkp://pool.sks-keyservers.net
21
gpg: key FAF6989E1BC16FEA: "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" not changed
22
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" not changed
23
gpg: key 7638F1FB2B2B08C4: "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" not changed
24
gpg: key EF5430F071E1B235: "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" not changed
25
gpg: key 63BC1CFE91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
26
gpg: key 9F597F4D21A56D5F: "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" not changed
27
gpg: key D441C977412B37AD: "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" not changed
28
gpg: Total number processed: 7
29
gpg:              unchanged: 7
30
**_Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues_**
31
Unexpected HTTP response: 404
32
Stacktrace:
33
Error: Unexpected HTTP response: 404
34
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8815:25
35
    at Generator.next (<anonymous>)
36
    at fulfilled (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8720:58)
37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by haikusw** [comment]
(Not my project. I just updated a comment in code that's part of a PR that previously built fine ¯\_(ツ)_/¯ )

**Comment by fwal** [comment]
Same as #196.

Basically GitHub bumped the version of Ubuntu that ubuntu-latest points to and older versions of Swift aren't available on that version.

**Comment by haikusw** [comment]
thanks
