### ISSUE TITLE
Support Swift 5.4.2

### ISSUE THREAD

**Issue by sidepelican** [fwal/setup-swift#280]
Is there any documents on the way for submitting a PR that supports the new Swift version?
We want to use Swift 5.4.2 but currenty not listed in https://github.com/fwal/setup-swift/blob/d43a564349d1341cd990cfbd70d94d63b8899475/src/swift-versions.ts#L5

**Comment by fwal** [comment]
Thanks for reaching out!
Yes, I'm currently working on automating the process so new releases automatically gets added.

In the mean time it has to be done manually (see #208 for an example).

I'll make sure it gets added during the weekend.

**Comment by sidepelican** [comment]
Thank you!!
