### ISSUE TITLE
Version 5.5 is not available 

### ISSUE THREAD

**Issue by freddy1h** [fwal/setup-swift#325]
I added this to my workflow and received an error
```
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.5"
```

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): macos-latest

```
Version "5.5" is not available
6
Stacktrace:
7
Error: Version "5.5" is not available
8
    at Object.verify (/Users/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:7935:15)
9
    at /Users/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2644:36
10
    at Generator.next (<anonymous>)
11
    at fulfilled (/Users/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2625:58)
```

**Comment by raytso** [comment]
I'm seeing a PR https://github.com/fwal/setup-swift/pull/315 to set the default version to `5.5`. Should address this bug before merging that?

**Comment by fwal** [comment]
@freddy1h Hi! Thanks for the report. I just released a new version that should fix this issue.
