### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by tjeerdintveen** [fwal/setup-swift#337]
**Describe the bug**
Hi, I'm suddenly getting this unexpected error.
https://github.com/tus/TUSKit/runs/4427491264?check_suite_focus=true

I am not sure what's causing it and it was working before. The weird thing is, I am using an identical config (only name is different) on a different project where the runner does run.

This one runs (different project): https://github.com/transloadit/TransloaditKit/blob/be842ba0561fe9e5ed14250fe460c8b1b08d40f9/.github/workflows/transloaditkit-ci.yml

Compared to yml of the failing project:
https://github.com/tus/TUSKit/blob/201c1c2801b3840a395833db20227d9cbf7ca7e9/.github/workflows/tuskit-ci.yml

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): [e.g. ubuntu-latest]
 macos-latest
 - Swift version (`swift-version`): [e.g. 5.2]
 5.3 and 5.3.2 fail
 
I would love to hear what I can do. Thanks!

**Comment by fwal** [comment]
Hi @tjeerdintveen, and thanks for the report! 

While I cannot directly answer why they fail, seeing that they are locked to the same commit, I would recommend switching to using tags instead as the version that is used is somewhat outdated.

Try changing to `- uses: fwal/setup-swift@1.10.0` and see if that helps.

**Comment by tjeerdintveen** [comment]
Thank you for the quick reply! Yeah we got that runner from the [Github docs](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift).

Unfortunately that version can't be found, is there a list of any that I can use?

Related error: https://github.com/tus/TUSKit/runs/4428200055?check_suite_focus=true

**Comment by fwal** [comment]
Oh wow, hade no idea this little action had made it into the official docs 😅
Yes I'm sorry I mis-typed the tag, it should be `- uses: fwal/setup-swift@v1.10.0` (notice the "v" before the version)

All available versions can be found in the [releases](https://github.com/fwal/setup-swift/releases) view.

**Comment by fwal** [comment]
I've opened an issue and pr to fix the docs https://github.com/github/docs/issues/12678

**Comment by tjeerdintveen** [comment]
Hi I think I should reopen. There is still something not right with the runner v1.10.0 it seems.
It fails on --enable-experimental-concurrency.
https://github.com/tus/TUSKit/runs/4429558221?check_suite_focus=true

But. If I build using `swift build -Xswiftc --disable-experimental-concurrency`, it still fails on it.
https://github.com/tus/TUSKit/runs/4430046178?check_suite_focus=true

Any clue on what I can do to make the runner run again? 

Cheers!

**Comment by fwal** [comment]
Great to hear that it started to work 🎉
Regarding the concurrency flags, I think they're available from Swift 5.5 and forward 🤔 (see https://github.com/apple/swift-evolution/blob/main/proposals/0304-structured-concurrency.md)

I'm closing this as it seems that the original issue is resolved, please feel free to reopen or create a new issue if you run into any further troubles. 👍🏻
