### ISSUE TITLE
Error: Unexpected error, unable to continue. Version "5.5.3" is not available

### ISSUE THREAD

**Issue by rogerluan** [fwal/setup-swift#366]
Hey 👋 

I'm facing this issue now:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/8419048/154801338-08927f77-9a5c-4729-9259-9ac45f67300e.png">

https://github.com/rogerluan/JSEN/runs/5252115325?check_suite_focus=true

Any clue what's going on? 🤔 5.5.3 should be available, right?

My workflow file can be found here: 

https://github.com/rogerluan/JSEN/blob/0db21351ddac65cc2347f68289f635618ca539f3/.github/workflows/run_tests.yml#L14

Thanks in advance! 🙏

**Comment by Nef10** [comment]
Same for me

**Comment by Nef10** [comment]
I also think I know why: With 1.13.0 there was no build performed, e.g. the files in disc have not been updated

**Comment by Nef10** [comment]
I opened a PR (#367) - here you can see a test run of it: https://github.com/Nef10/SwiftBeanCountRogersBankMapper/pull/66

**Comment by rogerluan** [comment]
Amazing!! Perhaps @fwal could merge your PR soon 🙏 
Thanks @Nef10 !

**Comment by fwal** [comment]
Hi @rogerluan & @Nef10, sorry about that! It seems like I didn't include the dist in the bump commit 🙈
Additionally, the integrity checks didn't warn either (although they failed).

I'll get this merged and deployed asap and then I'll add some more automations to this process.
