### ISSUE TITLE
Swift 5.6 not available

### ISSUE THREAD

**Issue by fwcd** [fwal/setup-swift#379]
**Describe the bug**
Despite the README indicating support for Swift 5.6, my workflow fails with

```
Run fwal/setup-swift@v1
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
Version "5.6" is not available
Stacktrace:
Error: Version "5.6" is not available
    at Object.verify (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8115:15)
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2740:36
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2721:58)
```

([see here](https://github.com/fwcd/swift-discord/runs/5573176896))

Any ideas?

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): ubuntu-latest
 - Swift version (`swift-version`): 5.6

**Comment by fwcd** [comment]
I think the issue is that `v1` doesn't point to `v1.14.0` yet.

**Comment by team172011** [comment]
I am facing the same issue with macOS-latest for swift version 5.6

**Comment by team172011** [comment]
like @fwcd mentioned the current solution would be set version explicit like:

```
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6"
```

**Comment by fwal** [comment]
Hi! Sorry everyone, the v1 failed to update without me noticing, it has been updated now!

As mentioned you can always use the exact version and I will eventually deprecate the `v1` tag once the project makes the jump to version `2.0`.

Optionally you can use [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to keep all your actions up-to-date automatically:
```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
```
