### ISSUE TITLE
Specifying "5.0" should not resolve "5.2.4"

### ISSUE THREAD

**Issue by mxcl** [fwal/setup-swift#95]
It should resolve 5.0.3 IMO.

If I wanted to get 5.2.4 I would specify `5` not `5.0`

**Comment by fwal** [comment]
I agree and resolving 5.0 to 5.0.3 is the expected behaviour. Could you provide the following information from your workflow yml:
 - Platform (`runs-on`): [e.g. ubuntu-latest]
 - Swift version (`swift-version`): [e.g. 5.2]

**Comment by mxcl** [comment]
It was `ubuntu-latest` and `swift-version: 5.0`

**Comment by mxcl** [comment]
Possibly it's a YAML thing? I didn't specify `'5.0'` but `5.0`?

**Comment by fwal** [comment]
I see, please beware that unquoted version numbers with a single decimal will be interpreted by yaml as a float e.g. "5"

**Comment by mxcl** [comment]
Yeah that makes sense.
